# Generated by Django 3.1.5 on 2021-02-14 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('guests', models.IntegerField(help_text='How many will be participating?')),
                ('size', models.IntegerField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('instant_book', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Cohort Locations',
            },
        ),
        migrations.CreateModel(
            name='CohortName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Cohort Name',
            },
        ),
        migrations.CreateModel(
            name='CohortRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Cohort Rules',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='cohort_photos')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cohort.cohort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='cohortLocations',
            field=models.ManyToManyField(blank=True, related_name='cohort', to='cohort.CohortLocations'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='cohortName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort', to='cohort.cohortname'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='cohortRules',
            field=models.ManyToManyField(blank=True, related_name='cohort', to='cohort.CohortRules'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='cohort_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to=settings.AUTH_USER_MODEL),
        ),
    ]
